### ISSUE TITLE
Checksum of the binary target

### ISSUE THREAD

**Issue by gianlucabertani** [dehesa/IG#1]
Hello Marcos,

thank you very much for this sample project, it's being really helpful.

I have one question: at Lightstreamer we now have a build producing XCframeworks for our supported platforms, to enable use from from SPM. The problem is: we need to publish their checksum to be specified as binary targets. Computing the checksum requires a _root package manifest_, or SPM raises an error. Obj-C frameworks don't require any such manifest, so it's not actually clear to which manifest it is referring when SPM raises this error.

Any advice? How did you compute the checksum for your sample Lightstreamer XCframework?

**Comment by dehesa** [comment]
Hi Gianluca,

I am not sure I understand your question. I will list below the steps needed for a binary target to be accessible through SPM. If this is not what you need, please rephrase your question.

1. Create a framework for each supported architecture and bundle them up in an xcframework.
    Please remember to create different frameworks for simulator and device code. [Here](https://medium.com/@er.mayursharma14/how-to-create-xcframework-855817f854cf) there is a good explanation on how to build xcframeworks.
2. If you haven't code-sign your frameworks, do this at this point.
    You can do this during compilation or with the `codesign` command-line tool. If the frameworks are not code-sign the OS will complain to the end-user when trying to run an executable.
3. Compress the xcframework in a zip file.
    You can use any program you like for this. macOS have a bundled zipper; you can right-click on the `Lightstreamer.xcframework` file and then select *compress item*. The outcome is not as compressed as it could be, though. You can do better with third-party programs or command-line apps.

Providing the zip file in your download page is already enough for any person wanting to use the xcframework. A developer wanting to integrate the code can choose any of the following two options:
- Use a local path in his/her system (no checksum required).
  1. Download the zip file from your website.
  2. Unzip it.
  3. Add the xcframework local path to the developer's SPM program.
      ```swift
      targets: [
          .binaryTarget(name: "Lightstreamer", path: "path/to/framework/Lightstreamer.xcframework")
      ]
      ```
      This is only intended for development purposes, though.
- Add it as a dependency to his/her SPM package.
  1. Download the zip file from your website.
  2. Compute the checksum through the SPM command-line tool.
      ```bash
      swift package compute-checksum Lightstreamer.zip
      ```
      Alternatively, you could have written the checksum outcome in the download page, so the developer don't have to do these two steps.
  3. Add the Lighstreamer URL and the checksum to his/her SPM manifest.
        ```swift
        targets: [
            .binaryTarget(name: "Lightstreamer", url: "https://www.lightstreamer.com/repo/distro/blah/blah/Lighstreamer.zip", checksum: "....")
        ]
        ```

If you want to go the extra-mile, and make it super easy for anyone using Swift to integrate with Lightstreamer, you could create your own SPM package and host it anywhere that support git projects (e.g. Github, Gitlab, etc). I will explain the steps for Github since it is what I know.
1. Create a Github project.
2. Add a REAME.md and LICENSE file.
3. Add a `Package.swift` file and append the following.
    ```swift
    // swift-tools-version:5.3
    import PackageDescription
    
    var package = Package(
        name: "Lightstreamer",
        platforms: [
            .macOS(.v11), .iOS(.v14), .tvOS(.v14), .watchOS(.v7)  // whatever you decide to support
        ],
        products: [
            .library(name: "Lightstreamer", targets: ["Lightstreamer"])
        ],
        dependencies: [],
        targets: [
            .binaryTarget(name: "Lightstreamer", url:"https://www.lightstreamer.com/repo/distro/blah/blah/Lighstreamer.zip", checksum: "fb40a5553b76bf87b447c84705f5630d1b860654a6af3cd0b4f2c8667a2b251c"),
        ]
    )   
    ```
4. Use git tags for any new version.
5. Any developer wanting to use Lightstreamer just need to add the following code to their projects.
    ```swift
    dependencies: [
        .package(url: "https://github.com/Lighstreamer/Lightstreamer.git", from: "2.1.2")
    ] // or whatever URL and version you decide to write (no checksum needed)
    ```

If you decide to take this route, I would recommend to append the zip file to the Github release (as I have done for this project). This way, it is easy to have proper versioning.

**Comment by gianlucabertani** [comment]
Thank you Marcos. Your explanation is very clear.

I'm still perplexed by this convention of adding a binary _target_ to the package descriptor of your own application to actually specify a _dependency_ from a binary built by someone else, but I guess this is how it's meant to work.

**Comment by dehesa** [comment]
It does make sense to me 😅 but I will concede that I spend most of my time on Swift & SPM, so it has become ingrained. As far as I understand, the SPM authors wanted to make the division between what the library builds (or use), defined in `targets`, and what it is actually exposed publicly, defined in `products`.

A developer wanting to use Lightstreamer doesn't know and/or doesn't really care how the library is provided. The developer just specifies in their SPM manifest:

```swift
dependencies: [.package(url: "https://github.com/Lighstreamer/Lightstreamer.git", from: "2.1.2")]
```

For your case, as a library provider with close source (i.e. pre-built binaries), it is a bit more convoluted (as explained in the previous posts). But that is not what 99% of developers needs to deal with.

In any case, thank you for taking the time to try to fix all this. I am looking forward being able to deliver Lightstreamer to all Apple platforms.
